clusteredMode: false

# images:
#   ## CloudBees CD/RO flow-server image tag to pull.
#   tag: "2024.06.0.175153_3.2.117_20240613"

##---------------------------------------------
## Flow storage configuration section
##---------------------------------------------
# serverName: cd-demo.cbflow.xyz
storage:
  volumes:
    serverPlugins:
      name: flow-server-shared
      accessMode: ReadWriteOnce
      # Storage class for plugins directory. Currently it has to be shared across server and web replicas.
      # Server and web are co-located using hard affinity rule for non clusteredMode. StorageClass is null here to ensure the same behavior across all cloud providers
      # (it forces storage class to fall back to  "default" disk based ReadWriteOnce platform specific storage class)
      storage: 5Gi

    repositoryStorage:
      storage: 10Gi

##---------------------------------------------
## Flow components/workloads configuration section
##---------------------------------------------
server:
  resources:
    limits:
      cpu: 1.5
    requests:
      cpu: 0.5
  autoscaling:
    enabled: true

# Install mariadb chart for demo mode
# and create a database and user for Flow to use.
# Note that the database user name and password
# specified in the `initdbScripts` section must
# match the values in the `database` section below.

mariadb:
  enabled:  true
  db:
    user: "flow"

database:
  dbName: "demo"
  dbUser: "flow"
  dbType: "mariadb"
  dbPort: 3306
  clusterEndpoint: "mariadb"
# externalEndpoint: ""

ingress:
  enabled: true
  # host: cd-demo.cbflow.xyz
  # certificate:
  #   existingSecret: cbdemo-tls-cert


# boundAgent:
#   images:
#     ## CloudBees CD/RO flow-server image tag to pull.
#     tag: "2024.06.0.175153_3.2.117_20240613"
